#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#
#app:
#  topic: kafka-spring-producer
#
#logging:
#  level:
#    root: WARN
#    org.springframework.web: INFO
#    com.memorynotfound: DEBUG